name: settlesmart
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - pip:
    - requests
    - flask
    - flask_pymongo
    - load_dotenv
