name: settlesmart
channels:
  - conda-forge
  - conda-canary
  - defaults
dependencies:
  - authlib=1.3.0
  - blinker=1.8.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.1.7
  - contourpy=1.3.0
  - cryptography=43.0.1
  - cycler=0.12.1
  - flask=3.0.3
  - fonttools=4.53.1
  - freetype=2.12.1
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - itsdangerous=2.2.0
  - jinja2=3.1.4
  - joblib=1.4.2
  - kiwisolver=1.4.7
  - lcms2=2.16
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx=19.1.0
  - libdeflate=1.21
  - libexpat=2.6.3
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libopenblas=0.3.27
  - libpng=1.6.44
  - libsqlite=3.46.1
  - libtiff=4.7.0
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libzlib=1.3.1
  - llvm-openmp=18.1.8
  - markupsafe=2.1.5
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - munkres=1.1.4
  - ncurses=6.5
  - numpy=2.1.1
  - openjpeg=2.5.2
  - openssl=3.3.2
  - packaging=24.1
  - pandas=2.2.3
  - pillow=10.4.0
  - pip=24.2
  - pthread-stubs=0.4
  - pycparser=2.22
  - pyparsing=3.1.4
  - pysocks=1.7.1
  - python=3.12.5
  - python-dateutil=2.9.0
  - python-dotenv=1.0.1
  - python-tzdata=2024.1
  - python_abi=3.12
  - pytz=2024.1
  - qhull=2020.2
  - readline=8.2
  - requests=2.32.3
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - setuptools=74.1.2
  - six=1.16.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tornado=6.4.1
  - tzdata=2024a
  - urllib3=2.2.3
  - werkzeug=3.0.4
  - wheel=0.44.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zipp=3.20.2
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - attrs==24.2.0
      - auth0-python==4.7.2
      - cachelib==0.13.0
      - dnspython==2.6.1
      - flask-pymongo==2.3.0
      - flask-session==0.8.0
      - frozenlist==1.4.1
      - msgspec==0.18.6
      - multidict==6.1.0
      - pyjwt==2.9.0
      - pymongo==4.9.1
      - yarl==1.11.1